PATHS_USER_ROOT ?= /home/tpw
PATHS_WEB_ROOT ?= $(PATHS_USER_ROOT)/public_html/kayak.test
PATHS_WEB_BASE ?= $(notdir $(PATHS_WEB_ROOT))
PATHS_LOCAL_ROOT ?= $(PATHS_USER_ROOT)/local
PATHS_FILES_ROOT ?= $(PATHS_USER_ROOT)/kayak.test

BINDIR ?= $(PATHS_USER_ROOT)/bin
CGIDIR ?= $(PATHS_WEB_ROOT)/cgi
LOCALLIB ?= $(PATHS_LOCAL_ROOT)/lib
LOCALINC ?= $(PATHS_LOCAL_ROOT)/include

# mysql config

MYSQL_CONFIG ?= mysql_config

# Program flags
#
INSTALLFLAGS ?= -b -p
