#! /bin/bash
#
# Create a new database
#
ROOT=`dirname $0`
TGT=$ROOT/../files/a.db

mkdir -p `dirname $TGT`
rm -f $TGT

$ROOT/mkOne $ROOT/master.txt \
	$ROOT/data.txt \
	$ROOT/levels.txt \
	$ROOT/translate.txt \
	$ROOT/stateCounty.txt 
