#! /bin/bash -x

ROOT=`dirname $0`/..

time make -C $ROOT/genDB install
time $ROOT/src/bin/cloneMaster
time $ROOT/src/bin/cloneData

time $ROOT/scripts/siteInfo

time $ROOT/src/bin/updateCalcs 48

time $ROOT/src/bin/updateLevels

time make -C $ROOT/genDB extra # AW Ids

time $ROOT/scripts/fetch
