#! /bin/bash -x

ROOT=/home/tpw/kayaking2

time make -C $ROOT/genDB install

time $ROOT/src/bin/cloneMySQL

# USGS site information update
time $ROOT/src/bin/fetch -u 'USGS1:http://waterdata.usgs.gov/nwis/inventory?state_cd=id&state_cd=or&state_cd=wa&site_tp_cd=ST&group_key=NONE&format=sitefile_output&sitefile_output_format=xml&column_name=agency_cd&column_name=site_no&column_name=station_nm&column_name=dec_lat_va&column_name=dec_long_va&column_name=state_cd&column_name=county_cd&column_name=alt_va&column_name=huc_cd&column_name=basin_cd&column_name=drain_area_va&list_of_search_criteria=state_cd%2Csite_tp_cd'

# USGS data from Idaho
time $ROOT/src/bin/fetch -u 'USGS0:http://waterservices.usgs.gov/nwis/iv/?format=waterml,2.0&stateCd=id&parameterCd=00060,00065,00010&siteType=ST'
# USGS data from Oregon
time $ROOT/src/bin/fetch -u 'USGS0:http://waterservices.usgs.gov/nwis/iv/?format=waterml,2.0&stateCd=or&parameterCd=00060,00065,00010&siteType=ST'
# USGS data from Washington
time $ROOT/src/bin/fetch -u 'USGS0:http://waterservices.usgs.gov/nwis/iv/?format=waterml,2.0&stateCd=wa&parameterCd=00060,00065,00010&siteType=ST'

time $ROOT/src/bin/updateCalcs 48

time $ROOT/src/bin/updateLevels

time make -C $ROOT/genDB extra # AW Ids
