#! /bin/bash -x

ROOT=/home/tpw/kayaking2

time make -C $ROOT/genDB install

time $ROOT/src/bin/cloneMySQL

time $ROOT/scripts/siteInfo

time $ROOT/src/bin/updateCalcs 48

time $ROOT/src/bin/updateLevels

time make -C $ROOT/genDB extra # AW Ids

time $ROOT/scripts/fetch
